### ISSUE TITLE
Fraud prevention

### ISSUE THREAD

**Issue by wlexiiii** [proximax-foundry/web-wallet-vuejs#605]
Advanced Features

Pull request, solve like in Symbol wallet (show warning)

[Additional warning for aggregate bonded announced by "third party" address · Issue #1719 · symbol/desktop-wallet](https://github.com/symbol/desktop-wallet/issues/1719) 

And this is a fraud using a SecretLock. SecretLock info isn't showed, so it looks like the user gets 500XYM. i think they fixed it to show Secret Lock info: [Additional warning for aggregate bonded announced by "third party" address · Issue #1719 · symbol/desktop-wallet](https://github.com/symbol/desktop-wallet/issues/1719#issuecomment-929928841)

**Comment by sleepyOwl14** [comment]
does not affect our wallet, we display all the transaction details
