### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by wlexiiii** [proximax-foundry/web-wallet-vuejs#608]
Important Features

**Confluence pages**
[https://nemspfs.atlassian.net/wiki/spaces/PT/pages/2441576558/Web+Wallet+Roadmap](url)

**Comment by Ghost-Slime** [comment]
PR Reference:

https://github.com/proximax-foundry/web-wallet-vuejs/pull/730

Screenshot:


![Image](https://user-images.githubusercontent.com/85566370/220247708-e10a073c-4e26-45a4-ba6c-f872f2fd87a5.png)



![Image](https://user-images.githubusercontent.com/85566370/220247867-72b4bffa-3e74-419c-b05f-e7f5bed21b4c.png)



![Image](https://user-images.githubusercontent.com/85566370/220247893-10e964a8-2326-4266-9f04-b16ec6c60df4.png)
