### ISSUE TITLE
DFMS Integration / File Storage tool

### ISSUE THREAD

**Issue by wlexiiii** [proximax-foundry/web-wallet-vuejs#613]
Basic features (Core?):

- Upload file

- Download file

- Rename file

- Delete file

- Create directory

- Rename directory

- Delete directory

Advanced features (SDK?):

- File encryption (normal account and multisignature if possible *)

- File decryption (normal account and multisignature if possible *)

- File name obfuscating (encrypt file name) (with extension) **

- Directory name obfuscating (encrypt file name) **

- Create and copy a link to the file to share with other people

File details (Core?):

- File name

- File size

- File (data) encrypted yes/no

- File name encrypted yes/no

- File type (extension)

- Share a drive with multiple people/accounts (including optional encryption)

** The user should see normal file/directory names (not obfuscated)

 

![Image](https://user-images.githubusercontent.com/86057280/197154834-9b7eaae5-b3ae-45e4-a586-dd227311e10f.png)

![Image](https://user-images.githubusercontent.com/86057280/197154869-1ae09455-3f0c-4863-9df5-354954d018b9.png)

**Comment by sleepyOwl14** [comment]
It need to be a separated desktop application. If possible, it is just integration with that application, with limited local connection/ communication.
