### ISSUE TITLE
Notification Sound

### ISSUE THREAD

**Issue by wlexiiii** [proximax-foundry/web-wallet-vuejs#615]
**Optional Features**

There is additional notification sound for transfer, namespace, and asset when the transactions are complete on angular wallet. It might be better to bring it to the vuejs wallet and make it customizeable for user to turn it on or off for the user on the settings.

Confluence pages -
[https://nemspfs.atlassian.net/wiki/spaces/PT/pages/2467528736/Angular+and+Vuejs+Web+Wallet+Comparison](url)

**Comment by Ghost-Slime** [comment]
PR Reference:

https://github.com/proximax-foundry/web-wallet-vuejs/pull/717
