### ISSUE TITLE
Fix asset supply not updated on modify asset transaction

### ISSUE THREAD

**Issue by wlexiiii** [proximax-foundry/web-wallet-vuejs#622]
The asset supply on modify asset supply page is not updated after the increase or decrease transaction is made.

![Image](https://user-images.githubusercontent.com/86057280/197157189-ff902baa-160f-4f5f-b1c5-cc586d23c55f.png)

![Image](https://user-images.githubusercontent.com/86057280/197157213-775c4d20-f3b6-4975-acad-a2048e31b228.png)

**Comment by Ghost-Slime** [comment]
**PR Reference:**

https://github.com/proximax-foundry/web-wallet-vuejs/pull/633

**Screenshots:**
Modify Asset Supply - Increase 500.


![Image](https://user-images.githubusercontent.com/85566370/199177894-88cc8f38-a642-48f4-85a8-82da13b28fdf.png)



![Image](https://user-images.githubusercontent.com/85566370/199178012-656437b0-a05d-467b-a664-a41edb7599c6.png)



![Image](https://user-images.githubusercontent.com/85566370/199178062-661d4a7c-8243-4f20-af8b-586cd6efe07e.png)

Modify Asset Supply - Decrease 1000.



![Image](https://user-images.githubusercontent.com/85566370/199178308-2a209de0-76cf-4abc-a8ad-9f2631f56e39.png)



![Image](https://user-images.githubusercontent.com/85566370/199178365-e3831c35-732f-4b30-be5c-c1721a0af8ea.png)
