### ISSUE TITLE
Account changed to primary after being refresh

### ISSUE THREAD

**Issue by wlexiiii** [proximax-foundry/web-wallet-vuejs#623]
![Image](https://user-images.githubusercontent.com/86057280/197157381-9e700915-604f-4de9-943e-2ba7005827ca.png)

![Image](https://user-images.githubusercontent.com/86057280/197157402-4bf3b25c-03cc-4c2f-b291-e1502c929a65.png)

**Comment by Ghost-Slime** [comment]
PR Reference:

https://github.com/proximax-foundry/web-wallet-vuejs/pull/670

Screenshots:


![Image](https://user-images.githubusercontent.com/85566370/206677840-754b9724-74ac-45cc-8908-77eee61261e3.png)
