### ISSUE TITLE
Asset balance show 0 at for newly created asset before refreshing the page and load 10k assets

### ISSUE THREAD

**Issue by SehKeat** [proximax-foundry/web-wallet-vuejs#624]

**Comment by Ghost-Slime** [comment]
PR Reference:

https://github.com/proximax-foundry/web-wallet-vuejs/pull/661

Screenshots:


![Image](https://user-images.githubusercontent.com/85566370/205560982-3b6dbd32-0182-40ac-884e-e24997ed0739.png)
