### ISSUE TITLE
Assets NaN in transfer page

### ISSUE THREAD

**Issue by winson-cell** [proximax-foundry/web-wallet-vuejs#691]
![Image](https://user-images.githubusercontent.com/59526011/213129076-c43842a5-1565-42c5-a600-78cf83b2e8ca.png)

Assets will change to NaN if delete is pressed when assets is 0

**Comment by SehKeat** [comment]
PR Reference:
https://github.com/proximax-foundry/web-wallet-vuejs/pull/690
