### ISSUE TITLE
Crash when sign out at display all account

### ISSUE THREAD

**Issue by SehKeat** [proximax-foundry/web-wallet-vuejs#694]
![Image](https://user-images.githubusercontent.com/85566370/215412355-b849f837-9aed-4345-8a82-8df4d3ca0b5d.png)

**Comment by Ghost-Slime** [comment]
PR Reference:

https://github.com/proximax-foundry/web-wallet-vuejs/pull/698

Screenshots:


![Image](https://user-images.githubusercontent.com/85566370/215412472-1289dac2-156c-457e-bb2b-208a63bfb716.png)
