### ISSUE TITLE
Name field in create namespace is not disabled when namespace is not selected

### ISSUE THREAD

**Issue by SehKeat** [proximax-foundry/web-wallet-vuejs#728]
![Image](https://user-images.githubusercontent.com/97232165/220037124-04ab2c0e-fc25-47a4-9b06-c93d3b63a591.png)

**Comment by Ghost-Slime** [comment]
PR Reference:

https://github.com/proximax-foundry/web-wallet-vuejs/pull/740

Screenshot:

![Image](https://user-images.githubusercontent.com/85566370/221497442-70a98706-ea23-41c8-9b96-0d1a965eb6ab.png)
