### ISSUE TITLE
Update cosignatories issues

### ISSUE THREAD

**Issue by Ghost-Slime** [proximax-foundry/web-wallet-vuejs#886]
Update cosignatories when scheme transactional values are adjusted to 0

![Image](https://github.com/proximax-foundry/web-wallet-vuejs/assets/85566370/65692356-e653-446d-8ecf-171ba4339147)

Update cosignatories when scheme account deletion values are adjusted to 0

![Image](https://github.com/proximax-foundry/web-wallet-vuejs/assets/85566370/8ab465b5-f5a0-4d76-ac6d-ba11970f7118)

**Comment by suencheah** [comment]
fixed in #895
